### ISSUE TITLE
Remove deprecated/soon-to-be removed rgbasm syntax

### ISSUE THREAD

**Issue by Rangi42** [AntonioND/ucity#5]
This project is built as part of rgbds's CI testing. It currently outputs many warnings about deprecated syntax, some of which will be outright removed in the next release. In particular, <code><i>name</i>: MACRO</code> should be <code>MACRO <i>name</i></code>.

**Comment by AntonioND** [comment]
Fair enough, even though if it was showing up in your CI it would have been nice to get a message whenever you added new warnings. How do you fix the warning about using ``halt``?

**Comment by Rangi42** [comment]
So, originally the behavior was to add `nop` after `halt` automatically, unless you opted out with the `-h` flag.

We're deprecating and removing that in a few phases. So far we've added the `-H` flag to opt *in* to this behavior. Currently the behavior is still on by default; the next release (0.7.0, coming soon) will have it off by default.

You could do one of two things:

1. Pass `-h` to opt out, and put `nop` after each `halt` yourself
2. Pass `-H` to opt in to auto-nop-after-halt

I'd recommend option 1, because once this whole behavior is removed, you'd need to do it anyway.

**Comment by AntonioND** [comment]
Well, this should take care of all my repositories:

https://github.com/AntonioND/ucity/commit/8a6342caf003652f3038a34834209e85026979c0

https://github.com/AntonioND/back-to-color/commit/5be53b89cbdbf2b9a14ac6c1770dc88555bd3a79

https://github.com/AntonioND/geometrix/commit/ec2138bc0a1c1d0995dcf0aab2ca8547379f1945

**Comment by AntonioND** [comment]
I'm closing this, feel free to open new issues if I need to make more changes!
