### ISSUE TITLE
Build is not deterministic

### ISSUE THREAD

**Issue by Rangi42** [AntonioND/ucity#7]
A deterministic build would be easier to test if it is correct.

Causes of this:

- In the Makefile, `$(shell find $(SOURCE) -type d -print)` and `$(wildcard $(dir)/*.asm)` may have different order on different machines (or the same machine at different times). Wrap them with `$(sort )`.
- mapgen.c uses a time-based random seed. It could instead use a fixed-value one, maybe passed from the commandline or otherwise defined in some easy-to-notice-and-edit place.
- ~~Something more that I haven't narrowed down. But just cloning ucity twice and doing two builds gives two different results.~~

https://github.com/gbdev/rgbds/pull/1384 has patched ucity to avoid these aspects.

**Comment by AntonioND** [comment]
Feel free to submit the patch that you are using in RGBDS. I'm ok even with a harcoded list of files. At this point I'm not developing this project, so I don't think that the list of files is ever going to change... 😅

`mapgen.c` is never used in the build process, it was just a prototype that I left in the repository for reference, so I don't think it matters.

> Something more that U haven't narrowed down. But just cloning ucity twice and doing two builds gives two different results.

Huh, that is weird...

**Comment by Rangi42** [comment]
> Feel free to submit the patch that you are using in RGBDS.

Thanks, done in #8!

**Comment by AntonioND** [comment]
Merged!
